from __future__ import annotations


COCKTAILS = [
    {
        "name": "Mojito",
        "ingredients": ["white rum", "lime", "mint", "sugar", "soda water"],
        "instructions": "Muddle mint, lime and sugar. Add rum and ice. Top with soda water and stir gently.",
        "style": "Refreshing",
        "flavor_profile": ["citrusy", "fresh", "light"],
        "occasions": ["Beach Day", "BBQ", "Casual Night"],
        "popularity": 10,
        "strength": "Medium",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "4 minutes",
    },
    {
        "name": "Daiquiri",
        "ingredients": ["white rum", "lime", "simple syrup"],
        "instructions": "Shake rum, lime juice and simple syrup with ice. Strain into a chilled coupe.",
        "style": "Citrusy",
        "flavor_profile": ["citrusy", "balanced", "classic"],
        "occasions": ["Dinner Party", "Date Night", "Casual Night"],
        "popularity": 9,
        "strength": "Medium",
        "glass": "Coupe",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Margarita",
        "ingredients": ["tequila", "lime", "orange liqueur"],
        "instructions": "Shake tequila, lime juice and orange liqueur with ice. Strain into a salt-rimmed glass.",
        "style": "Citrusy",
        "flavor_profile": ["citrusy", "bright", "salty"],
        "occasions": ["BBQ", "Beach Day", "Celebration"],
        "popularity": 10,
        "strength": "Medium",
        "glass": "Rocks",
        "difficulty": "Easy",
        "prep_time": "4 minutes",
    },
    {
        "name": "Caipirinha",
        "ingredients": ["cachaca", "lime", "sugar"],
        "instructions": "Muddle lime and sugar in a glass. Add cachaca and ice. Stir well.",
        "style": "Refreshing",
        "flavor_profile": ["citrusy", "fresh", "sweet"],
        "occasions": ["BBQ", "Beach Day", "Casual Night"],
        "popularity": 9,
        "strength": "Medium",
        "glass": "Rocks",
        "difficulty": "Easy",
        "prep_time": "4 minutes",
    },
    {
        "name": "Old Fashioned",
        "ingredients": ["bourbon", "sugar", "angostura bitters"],
        "instructions": "Stir sugar and bitters. Add bourbon and ice. Stir and garnish with orange peel.",
        "style": "Strong",
        "flavor_profile": ["spirit-forward", "bitter", "aromatic"],
        "occasions": ["Date Night", "Dinner Party", "Casual Night"],
        "popularity": 10,
        "strength": "Strong",
        "glass": "Rocks",
        "difficulty": "Medium",
        "prep_time": "5 minutes",
    },
    {
        "name": "Negroni",
        "ingredients": ["gin", "campari", "sweet vermouth"],
        "instructions": "Stir all ingredients with ice. Strain over fresh ice and garnish with orange peel.",
        "style": "Bitter",
        "flavor_profile": ["bitter", "herbal", "balanced"],
        "occasions": ["Dinner Party", "Date Night", "Casual Night"],
        "popularity": 10,
        "strength": "Strong",
        "glass": "Rocks",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Whiskey Sour",
        "ingredients": ["whiskey", "lemon", "simple syrup"],
        "instructions": "Shake whiskey, lemon juice and simple syrup with ice. Strain into a rocks glass.",
        "style": "Citrusy",
        "flavor_profile": ["citrusy", "smooth", "balanced"],
        "occasions": ["Dinner Party", "Date Night", "Casual Night"],
        "popularity": 9,
        "strength": "Medium",
        "glass": "Rocks",
        "difficulty": "Easy",
        "prep_time": "4 minutes",
    },
    {
        "name": "Gin and Tonic",
        "ingredients": ["gin", "tonic water", "lime"],
        "instructions": "Build gin and tonic water over ice. Garnish with lime.",
        "style": "Refreshing",
        "flavor_profile": ["bitter", "fresh", "light"],
        "occasions": ["Casual Night", "BBQ", "Beach Day"],
        "popularity": 10,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "2 minutes",
    },
    {
        "name": "Moscow Mule",
        "ingredients": ["vodka", "lime", "ginger beer"],
        "instructions": "Build vodka and lime over ice. Top with ginger beer and stir gently.",
        "style": "Refreshing",
        "flavor_profile": ["spicy", "citrusy", "fresh"],
        "occasions": ["Casual Night", "BBQ", "Watching Sports"],
        "popularity": 9,
        "strength": "Medium",
        "glass": "Copper Mug",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Cosmopolitan",
        "ingredients": ["vodka", "orange liqueur", "cranberry juice", "lime"],
        "instructions": "Shake all ingredients with ice. Strain into a chilled cocktail glass.",
        "style": "Citrusy",
        "flavor_profile": ["bright", "fruity", "balanced"],
        "occasions": ["Date Night", "Celebration", "Dinner Party"],
        "popularity": 8,
        "strength": "Medium",
        "glass": "Martini",
        "difficulty": "Medium",
        "prep_time": "4 minutes",
    },
    {
        "name": "Espresso Martini",
        "ingredients": ["vodka", "coffee liqueur", "espresso", "simple syrup"],
        "instructions": "Shake hard with ice. Strain into a chilled coupe.",
        "style": "Sweet",
        "flavor_profile": ["coffee", "rich", "smooth"],
        "occasions": ["Date Night", "Celebration", "Dinner Party"],
        "popularity": 10,
        "strength": "Medium",
        "glass": "Coupe",
        "difficulty": "Medium",
        "prep_time": "5 minutes",
    },
    {
        "name": "Piña Colada",
        "ingredients": ["white rum", "pineapple juice", "coconut cream"],
        "instructions": "Blend or shake all ingredients with ice. Serve in a chilled glass.",
        "style": "Tropical",
        "flavor_profile": ["sweet", "creamy", "tropical"],
        "occasions": ["Beach Day", "Celebration", "Casual Night"],
        "popularity": 9,
        "strength": "Medium",
        "glass": "Hurricane",
        "difficulty": "Easy",
        "prep_time": "5 minutes",
    },
    {
        "name": "Mai Tai",
        "ingredients": ["rum", "lime", "orange liqueur", "orgeat syrup"],
        "instructions": "Shake all ingredients with ice. Strain over crushed ice and garnish.",
        "style": "Tropical",
        "flavor_profile": ["nutty", "citrusy", "tropical"],
        "occasions": ["Beach Day", "Celebration", "Casual Night"],
        "popularity": 8,
        "strength": "Strong",
        "glass": "Rocks",
        "difficulty": "Medium",
        "prep_time": "5 minutes",
    },
    {
        "name": "Aperol Spritz",
        "ingredients": ["aperol", "prosecco", "soda water"],
        "instructions": "Build over ice with prosecco, Aperol and soda water. Stir gently.",
        "style": "Refreshing",
        "flavor_profile": ["bitter", "light", "sparkling"],
        "occasions": ["Beach Day", "Dinner Party", "Casual Night"],
        "popularity": 10,
        "strength": "Light",
        "glass": "Wine Glass",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Martini",
        "ingredients": ["gin", "dry vermouth"],
        "instructions": "Stir gin and dry vermouth with ice. Strain into a chilled martini glass.",
        "style": "Strong",
        "flavor_profile": ["dry", "spirit-forward", "classic"],
        "occasions": ["Date Night", "Dinner Party", "Celebration"],
        "popularity": 9,
        "strength": "Strong",
        "glass": "Martini",
        "difficulty": "Medium",
        "prep_time": "4 minutes",
    },
    {
        "name": "Manhattan",
        "ingredients": ["rye whiskey", "sweet vermouth", "angostura bitters"],
        "instructions": "Stir all ingredients with ice. Strain into a coupe and garnish with cherry.",
        "style": "Strong",
        "flavor_profile": ["rich", "aromatic", "spirit-forward"],
        "occasions": ["Date Night", "Dinner Party"],
        "popularity": 9,
        "strength": "Strong",
        "glass": "Coupe",
        "difficulty": "Medium",
        "prep_time": "4 minutes",
    },
    {
        "name": "Bloody Mary",
        "ingredients": ["vodka", "tomato juice", "lemon", "worcestershire sauce", "hot sauce"],
        "instructions": "Build all ingredients over ice and stir. Garnish with celery or lemon.",
        "style": "Savory",
        "flavor_profile": ["savory", "spicy", "bold"],
        "occasions": ["Brunch", "Casual Night"],
        "popularity": 8,
        "strength": "Medium",
        "glass": "Highball",
        "difficulty": "Medium",
        "prep_time": "5 minutes",
    },
    {
        "name": "Paloma",
        "ingredients": ["tequila", "grapefruit soda", "lime"],
        "instructions": "Build tequila and lime over ice. Top with grapefruit soda and stir gently.",
        "style": "Refreshing",
        "flavor_profile": ["citrusy", "light", "sparkling"],
        "occasions": ["Beach Day", "BBQ", "Casual Night"],
        "popularity": 9,
        "strength": "Medium",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Tom Collins",
        "ingredients": ["gin", "lemon", "simple syrup", "soda water"],
        "instructions": "Shake gin, lemon and syrup with ice. Strain into a highball and top with soda.",
        "style": "Refreshing",
        "flavor_profile": ["citrusy", "light", "sparkling"],
        "occasions": ["BBQ", "Beach Day", "Casual Night"],
        "popularity": 8,
        "strength": "Medium",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "4 minutes",
    },
    {
        "name": "French 75",
        "ingredients": ["gin", "lemon", "simple syrup", "champagne"],
        "instructions": "Shake gin, lemon and syrup with ice. Strain into flute and top with champagne.",
        "style": "Refreshing",
        "flavor_profile": ["sparkling", "citrusy", "elegant"],
        "occasions": ["Celebration", "Date Night", "Dinner Party"],
        "popularity": 8,
        "strength": "Medium",
        "glass": "Flute",
        "difficulty": "Medium",
        "prep_time": "4 minutes",
    },
    {
        "name": "Sazerac",
        "ingredients": ["rye whiskey", "sugar", "peychaud bitters", "absinthe"],
        "instructions": "Stir whiskey, sugar and bitters with ice. Rinse glass with absinthe and strain.",
        "style": "Strong",
        "flavor_profile": ["spirit-forward", "herbal", "aromatic"],
        "occasions": ["Date Night", "Dinner Party"],
        "popularity": 7,
        "strength": "Strong",
        "glass": "Rocks",
        "difficulty": "Advanced",
        "prep_time": "6 minutes",
    },
    {
        "name": "Mint Julep",
        "ingredients": ["bourbon", "mint", "sugar"],
        "instructions": "Muddle mint and sugar. Add bourbon and crushed ice. Stir until chilled.",
        "style": "Refreshing",
        "flavor_profile": ["fresh", "sweet", "spirit-forward"],
        "occasions": ["BBQ", "Casual Night"],
        "popularity": 7,
        "strength": "Strong",
        "glass": "Julep Cup",
        "difficulty": "Medium",
        "prep_time": "5 minutes",
    },
    {
        "name": "Dark and Stormy",
        "ingredients": ["dark rum", "ginger beer", "lime"],
        "instructions": "Build rum and lime over ice. Top with ginger beer and stir gently.",
        "style": "Refreshing",
        "flavor_profile": ["spicy", "citrusy", "bold"],
        "occasions": ["BBQ", "Watching Sports", "Casual Night"],
        "popularity": 8,
        "strength": "Medium",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Cuba Libre",
        "ingredients": ["rum", "cola", "lime"],
        "instructions": "Build rum and lime over ice. Top with cola and stir gently.",
        "style": "Refreshing",
        "flavor_profile": ["sweet", "citrusy", "easy"],
        "occasions": ["Casual Night", "BBQ", "Watching Sports"],
        "popularity": 9,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "2 minutes",
    },
    {
        "name": "Tequila Sunrise",
        "ingredients": ["tequila", "orange juice", "grenadine"],
        "instructions": "Build tequila and orange juice over ice. Slowly add grenadine for a layered effect.",
        "style": "Sweet",
        "flavor_profile": ["fruity", "sweet", "bright"],
        "occasions": ["Beach Day", "Celebration", "Casual Night"],
        "popularity": 8,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Sea Breeze",
        "ingredients": ["vodka", "cranberry juice", "grapefruit juice"],
        "instructions": "Build all ingredients over ice and stir gently.",
        "style": "Refreshing",
        "flavor_profile": ["fruity", "tart", "light"],
        "occasions": ["Beach Day", "Casual Night"],
        "popularity": 7,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Sex on the Beach",
        "ingredients": ["vodka", "peach schnapps", "orange juice", "cranberry juice"],
        "instructions": "Shake or build all ingredients over ice. Serve in a highball glass.",
        "style": "Sweet",
        "flavor_profile": ["fruity", "sweet", "easy"],
        "occasions": ["Beach Day", "Celebration", "Casual Night"],
        "popularity": 8,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "White Russian",
        "ingredients": ["vodka", "coffee liqueur", "cream"],
        "instructions": "Build vodka and coffee liqueur over ice. Float cream and stir gently.",
        "style": "Sweet",
        "flavor_profile": ["creamy", "coffee", "rich"],
        "occasions": ["Casual Night", "Date Night"],
        "popularity": 8,
        "strength": "Medium",
        "glass": "Rocks",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Black Russian",
        "ingredients": ["vodka", "coffee liqueur"],
        "instructions": "Build vodka and coffee liqueur over ice and stir.",
        "style": "Strong",
        "flavor_profile": ["coffee", "rich", "spirit-forward"],
        "occasions": ["Casual Night", "Date Night"],
        "popularity": 7,
        "strength": "Strong",
        "glass": "Rocks",
        "difficulty": "Easy",
        "prep_time": "2 minutes",
    },
]
