    {
        "name": "Long Island Iced Tea",
        "ingredients": ["vodka", "gin", "rum", "tequila", "triple sec", "lemon", "cola"],
        "instructions": "Shake spirits, triple sec and lemon with ice. Strain into a highball and top with cola.",
        "style": "Strong",
        "flavor_profile": ["strong", "citrusy", "sweet"],
        "occasions": ["Celebration", "Casual Night"],
        "popularity": 8,
        "strength": "Strong",
        "glass": "Highball",
        "difficulty": "Medium",
        "prep_time": "5 minutes",
    },
    {
        "name": "Americano",
        "ingredients": ["campari", "sweet vermouth", "soda water"],
        "instructions": "Build over ice and top with soda water. Garnish with orange.",
        "style": "Bitter",
        "flavor_profile": ["bitter", "light", "sparkling"],
        "occasions": ["Dinner Party", "Casual Night"],
        "popularity": 7,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Boulevardier",
        "ingredients": ["bourbon", "campari", "sweet vermouth"],
        "instructions": "Stir all ingredients with ice and strain over fresh ice.",
        "style": "Bitter",
        "flavor_profile": ["bitter", "rich", "spirit-forward"],
        "occasions": ["Date Night", "Dinner Party"],
        "popularity": 8,
        "strength": "Strong",
        "glass": "Rocks",
        "difficulty": "Easy",
        "prep_time": "4 minutes",
    },
    {
        "name": "Sidecar",
        "ingredients": ["cognac", "orange liqueur", "lemon"],
        "instructions": "Shake with ice and strain into a coupe.",
        "style": "Citrusy",
        "flavor_profile": ["citrusy", "elegant", "balanced"],
        "occasions": ["Date Night", "Dinner Party"],
        "popularity": 7,
        "strength": "Medium",
        "glass": "Coupe",
        "difficulty": "Medium",
        "prep_time": "4 minutes",
    },
    {
        "name": "Bellini",
        "ingredients": ["prosecco", "peach puree"],
        "instructions": "Pour peach puree into a flute and top gently with prosecco.",
        "style": "Sweet",
        "flavor_profile": ["fruity", "sparkling", "light"],
        "occasions": ["Brunch", "Celebration"],
        "popularity": 8,
        "strength": "Light",
        "glass": "Flute",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Kir Royale",
        "ingredients": ["champagne", "creme de cassis"],
        "instructions": "Add creme de cassis to a flute and top with champagne.",
        "style": "Sweet",
        "flavor_profile": ["fruity", "sparkling", "elegant"],
        "occasions": ["Celebration", "Date Night"],
        "popularity": 7,
        "strength": "Light",
        "glass": "Flute",
        "difficulty": "Easy",
        "prep_time": "2 minutes",
    },
    {
        "name": "Rum Punch",
        "ingredients": ["rum", "lime", "orange juice", "pineapple juice", "grenadine"],
        "instructions": "Shake or build all ingredients over ice. Garnish with fruit.",
        "style": "Tropical",
        "flavor_profile": ["fruity", "sweet", "tropical"],
        "occasions": ["Beach Day", "BBQ", "Celebration"],
        "popularity": 8,
        "strength": "Medium",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "4 minutes",
    },
    {
        "name": "Hugo Spritz",
        "ingredients": ["prosecco", "elderflower liqueur", "soda water", "mint", "lime"],
        "instructions": "Build over ice and stir gently. Garnish with mint and lime.",
        "style": "Refreshing",
        "flavor_profile": ["floral", "fresh", "sparkling"],
        "occasions": ["Beach Day", "Brunch", "Casual Night"],
        "popularity": 8,
        "strength": "Light",
        "glass": "Wine Glass",
        "difficulty": "Easy",
        "prep_time": "3 minutes",
    },
    {
        "name": "Garibaldi",
        "ingredients": ["campari", "orange juice"],
        "instructions": "Build Campari and fluffy orange juice over ice.",
        "style": "Bitter",
        "flavor_profile": ["bitter", "citrusy", "light"],
        "occasions": ["Brunch", "Casual Night"],
        "popularity": 7,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "2 minutes",
    },
    {
        "name": "Ranch Water",
        "ingredients": ["tequila", "lime", "soda water"],
        "instructions": "Build tequila and lime over ice. Top with soda water.",
        "style": "Refreshing",
        "flavor_profile": ["light", "citrusy", "dry"],
        "occasions": ["BBQ", "Beach Day", "Casual Night"],
        "popularity": 8,
        "strength": "Light",
        "glass": "Highball",
        "difficulty": "Easy",
        "prep_time": "2 minutes",
    },
]


def get_cocktails() -> list[dict]:
    return COCKTAILS
